[package]
edition = "2021"
name = "basicforce"
version = "0.1.0"

[lib]
name = "basicforce"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
serde = {version = "1", features = ["derive"]}
